export const CONTACT_EMAIL = "kontakt@zdalnypsycholog.pl";
export const PHONE_NUMBER = "+48 695 163 484";
export const PHONE_HREF = "tel:+48695163484";
export const PHONE_EVENT_LABEL = "tel:+48695163484";
export const WHATSAPP_LABEL = "WhatsApp dostępny";
export const WHATSAPP_URL = "https://wa.me/48695163484";
export const FALLBACK_BOOKING_URL = "https://calendly.com/szczebelm/konsultacja-psychologiczna";
export const BOOKING_LABEL = "Wybierz termin konsultacji";
export const BOOKING_LANDING_URL = "/polacy-za-granica/#rezerwacja";
export const THANK_YOU_BOOKING_PATH = "/dziekujemy-za-rezerwacje/";
export const CALENDESK_BOOKING_URL = process.env.NEXT_PUBLIC_CALENDESK_BOOKING_URL?.trim() || FALLBACK_BOOKING_URL;
export const CALENDESK_EMBED_URL = process.env.NEXT_PUBLIC_CALENDESK_EMBED_URL?.trim() ?? "";
export const BOOKING_ENABLED = process.env.NEXT_PUBLIC_BOOKING_ENABLED === "true" || Boolean(CALENDESK_BOOKING_URL);
