export const CONTACT_EMAIL = "kontakt@zdalnypsycholog.pl";
export const PHONE_NUMBER = "+48 695 163 484";
export const PHONE_HREF = "tel:+48695163484";
export const PHONE_EVENT_LABEL = "tel:+48695163484";
export const WHATSAPP_LABEL = "WhatsApp dostępny";
export const WHATSAPP_URL = "https://wa.me/48695163484";
export const BOOKING_LABEL = "Wybierz termin konsultacji";
export const BOOKING_LANDING_URL = "/rezerwacja";
export const THANK_YOU_BOOKING_PATH = "/rezerwacja-potwierdzona/";
